apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: go-engine-svc
  labels:
    app: go-engine-svc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-engine-svc
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 70