apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: go-engine-svc
  newTag: "1.0"

resources:
- deployment.yaml
- service.yaml
- serviceAccount.yaml
- ingress.yaml
- hpa.yaml
- vpa.yaml
- pdb.yaml

