apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: go-engine-svc
spec:
  targetRef:
    apiVersion: "extensions/v1"
    kind: Deployment
    name: go-engine-svc
  upadatePolicy:
    updateMode: Off