DROP ROLE IF EXISTS isgogolgo132;
CREATE ROLE isgogolgo132 WITH LOGIN PASSWORD 'isgogolgo132';
ALTER USER isgogolgo132 CREATEDB;
ALTER USER isgogolgo132 CREATEROLE;

DROP DATABASE IF EXISTS EngineDB2;
CREATE DATABASE EngineDB2;