apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "go-gorilla-restsvc.fullname" . }}
  namespace: {{ .Values.namespace.name }}
spec:
  gateways:
    - {{ include "go-gorilla-restsvc.fullname" .}} 
  hosts:
    - "*"
  http:
    - match:
{{- range .Values.ingressGateway.matchPrefix }}
      - uri:
          prefix: {{ . | quote }}
{{- end }}
      route:
      - destination:
          host: {{ include "go-gorilla-restsvc.fullname" .}}
          port: 
            number: {{ .Values.ingressGateway.port }}
{{- if .Values.retries }}
      retries:
{{ toYaml .Values.retries | indent 8 }}
      timeout: {{ required "You must specify an overall timeout to use retries" .Values.overallTimeout}}
{{- else if .Values.overallTimeout }}
      timeout: {{ .Values.overallTimeout }}
{{- end }}