ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: istio

  tls: []

  paths:
    - path: /
      pathType: Prefix
      backend:
        service: 
          name: go-gorilla-restsvc-postgres
          port:
            number: 80