{{- if .Values.vpaAutoscaling.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "go-gorilla-restsvc-postgres.fullname" . }}
  namespace: {{ .Values.namespace.name }}
spec:
  targetRef: 
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ include "go-gorilla-restsvc-postgres.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.vpaAutoscaling.updatePolicy.updateMode | quote }}
{{- end }}