{{- if .Values.deploymentConfig.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "go-gorilla-restsvc-postgres.fullname" . }}-config"
data:
  dataStoreConnectionConfig:
{{- end }}