{{- if .Values.deploymentConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "go-gorilla-restsvc-postgres.fullname" . }}-config"
{{- with .Values.deploymentConfig.connectionConfig }}
data:
 {{- toYaml . | nindent 4 }}
{{- end}} 
{{- end }}
