apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-gorilla-restsvc.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "go-gorilla-restsvc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "go-gorilla-restsvc.selectorLabels" . | nindent 4 }}